/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.BloodBank;

import Buisness.Bloodbank.Organisation.InchargeOrganisation;
import Buisness.EcoSystem;
import Buisness.Enterprise.BloodbankEnterprise;
import Buisness.Network.Network;
import Buisness.UserAccount.UserAccount;
import Business.Hospital.Organisation.NurseOrganisation;
import UserInterface.Nurse.NurseBloodBankResponseJPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author aviti
 */
public class BloodBankInchargeLandingJPanel extends javax.swing.JPanel {
 private JPanel displayJPanel;
    private UserAccount userAccount;
    private InchargeOrganisation organisation;
   
    private EcoSystem system;
    private Network net;
    private BloodbankEnterprise enterprise;
    private UserAccount acc;
    /**
     * Creates new form BloodBankInchargeLandingJPanel
     */
   
    public BloodBankInchargeLandingJPanel(JPanel displayJPanel, UserAccount account, InchargeOrganisation inchargeOrganisation, BloodbankEnterprise bloodbankEnterprise, Network network, EcoSystem business) {
        initComponents();
        
        this.displayJPanel=displayJPanel;
       this.organisation = inchargeOrganisation;
        this.userAccount = account;
        this.enterprise = bloodbankEnterprise;
        this.system = business;
        this.net=network;
      //  this.acc=acc;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ViewRequestjButton = new javax.swing.JButton();
        GoToInventoryjButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createTitledBorder("BBI Landing Area"));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ViewRequestjButton.setText("View Requests");
        ViewRequestjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewRequestjButtonActionPerformed(evt);
            }
        });
        add(ViewRequestjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 125, 155, 66));

        GoToInventoryjButton.setText("Go To Inventory");
        GoToInventoryjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoToInventoryjButtonActionPerformed(evt);
            }
        });
        add(GoToInventoryjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 209, 155, 66));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel1.setText("BLOOD BANK INCHARGE");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 38, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void ViewRequestjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewRequestjButtonActionPerformed
        
         BloodBankInchargeWorkAreaJPanel bbi = new BloodBankInchargeWorkAreaJPanel(displayJPanel,userAccount,(InchargeOrganisation)organisation,enterprise,net,system);
        displayJPanel.add("BloodBankInchargeWorkAreaJPanel", bbi);
        CardLayout layout = (CardLayout) displayJPanel.getLayout();
        layout.next(displayJPanel);
        
               
    }//GEN-LAST:event_ViewRequestjButtonActionPerformed

    private void GoToInventoryjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoToInventoryjButtonActionPerformed
        // TODO add your handling code here:
        BloodBankInventoryJPanel bbin = new BloodBankInventoryJPanel(displayJPanel,userAccount,(InchargeOrganisation)organisation,enterprise,net,system);
        displayJPanel.add("BloodBankInventoryJPanel", bbin);
        CardLayout layout = (CardLayout) displayJPanel.getLayout();
        layout.next(displayJPanel);
        
        
    }//GEN-LAST:event_GoToInventoryjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GoToInventoryjButton;
    private javax.swing.JButton ViewRequestjButton;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
