/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Patient;

import Buisness.EcoSystem;
import Buisness.UserInfo.*;
import Business.Utilities.SendEmailUtility;
import java.awt.CardLayout;
import java.awt.Image;
import java.io.File;
import java.util.Date;
import java.util.Random;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author sarthakgoel
 */
public class CreatePatientAccountJPanel extends javax.swing.JPanel 
{
    private JPanel displayJPanel;
    private EcoSystem system;
    private PatientDirectory patientDir;

    /**
     * Creates new form CreatePatientAccount
     */
    public CreatePatientAccountJPanel(JPanel displayJPanel, EcoSystem system) 
    {
        initComponents();
        this.system=system;
        this.displayJPanel=displayJPanel;
        this.patientDir = system.getPatientDir();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblName = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        lblPhoneNumber = new javax.swing.JLabel();
        lblDOB = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        lblCity = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblState = new javax.swing.JLabel();
        lblZipCode = new javax.swing.JLabel();
        lblPhoto = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        txtCity = new javax.swing.JTextField();
        txtZipCode = new javax.swing.JTextField();
        txtState = new javax.swing.JTextField();
        uploadPicBtn = new javax.swing.JButton();
        maleRadioBtn = new javax.swing.JRadioButton();
        femaleRadioBtn = new javax.swing.JRadioButton();
        btnCreate = new javax.swing.JButton();
        lblUserPhoto = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtBloodGroup = new javax.swing.JTextField();
        lblBloodGroup = new javax.swing.JLabel();
        txtemailAddress = new javax.swing.JTextField();
        comboMM = new javax.swing.JComboBox();
        comboDD1 = new javax.swing.JComboBox();
        ComboYY = new javax.swing.JComboBox();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createTitledBorder("Patient"));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblName.setText("Patient's Name");
        add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 95, -1, -1));

        lblGender.setText("Gender");
        add(lblGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 124, -1, -1));

        lblPhoneNumber.setText("Phone Number");
        add(lblPhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 161, -1, -1));

        lblDOB.setText("Date Of Birth");
        add(lblDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 204, -1, -1));

        lblAddress.setText("Address Line1");
        add(lblAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 242, -1, -1));

        lblCity.setText("City");
        add(lblCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 280, -1, -1));

        lblTitle.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lblTitle.setText("CREATE PATIENT ACCOUNT");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 22, 213, 35));

        lblState.setText("State");
        add(lblState, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 318, -1, -1));

        lblZipCode.setText("ZipCode");
        add(lblZipCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 351, -1, -1));

        lblPhoto.setText("Upload Photo");
        add(lblPhoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 393, -1, -1));

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 92, 159, -1));

        txtPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneActionPerformed(evt);
            }
        });
        add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 161, 159, -1));
        add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 239, 159, -1));
        add(txtCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 277, 159, -1));
        add(txtZipCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 350, 159, -1));
        add(txtState, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 313, 159, -1));

        uploadPicBtn.setText("Browse");
        uploadPicBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadPicBtnActionPerformed(evt);
            }
        });
        add(uploadPicBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 388, 159, -1));

        maleRadioBtn.setBackground(new java.awt.Color(255, 255, 255));
        maleRadioBtn.setText("Male");
        maleRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleRadioBtnActionPerformed(evt);
            }
        });
        add(maleRadioBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, -1, -1));

        femaleRadioBtn.setBackground(new java.awt.Color(255, 255, 255));
        femaleRadioBtn.setText("Female");
        femaleRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleRadioBtnActionPerformed(evt);
            }
        });
        add(femaleRadioBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 120, -1, -1));

        btnCreate.setText("CreateProfile>>");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });
        add(btnCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 531, -1, -1));
        add(lblUserPhoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(497, 85, -1, -1));

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 531, -1, -1));

        jLabel1.setText("Email Address");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 429, -1, -1));
        add(txtBloodGroup, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 467, 159, -1));

        lblBloodGroup.setText("Blood Group");
        add(lblBloodGroup, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 470, -1, -1));
        add(txtemailAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 429, 159, -1));

        comboMM.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        comboMM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboMMActionPerformed(evt);
            }
        });
        add(comboMM, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 201, -1, -1));

        comboDD1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        add(comboDD1, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 201, -1, -1));

        ComboYY.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011" }));
        add(ComboYY, new org.netbeans.lib.awtextra.AbsoluteConstraints(281, 201, -1, -1));
    }// </editor-fold>//GEN-END:initComponents
 public boolean passwordValidation()
    {
        Pattern pattern1 = Pattern.compile("(A|B|AB|O|a|b|o|ab)[+-]");
        Matcher matcher1 = pattern1.matcher(txtBloodGroup.getText());
        
        boolean result = matcher1.matches();
        
        return result;
    }
    
    private void uploadPicBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadPicBtnActionPerformed
        try
        {
            JFileChooser userpic = new JFileChooser();
            userpic.showOpenDialog(null);
            File selectedpic = userpic.getSelectedFile();
            String fileName = selectedpic.getAbsolutePath();
            ImageIcon img = new ImageIcon(fileName);
            Image newimage = img.getImage().getScaledInstance(150, 150, Image.SCALE_DEFAULT);
            ImageIcon newicon = new ImageIcon(newimage);

            lblUserPhoto.setIcon(newicon);         
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Photo can not be uploaded. \n Try Again!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_uploadPicBtnActionPerformed

    private void maleRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleRadioBtnActionPerformed
        femaleRadioBtn.setSelected(false);
    }//GEN-LAST:event_maleRadioBtnActionPerformed

    private void femaleRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleRadioBtnActionPerformed
        maleRadioBtn.setSelected(false);
        
    }//GEN-LAST:event_femaleRadioBtnActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        
     try{   
        String dd,mm,yy;
           dd = (String)comboDD1.getSelectedItem();
           mm = (String)comboMM.getSelectedItem();
           yy = (String)ComboYY.getSelectedItem();
           int x,y,z;
           x = Integer.parseInt(dd);
           y = Integer.parseInt(mm);
           z = Integer.parseInt(yy);
           
        String name = txtName.getText();
        String gender = getGender();
        String phone = txtPhone.getText();
        String city = txtCity.getText();
        String state = txtState.getText();
        String address = txtAddress.getText();
        String email = txtemailAddress.getText();
        int zipCode = Integer.parseInt(txtZipCode.getText());
     
    if (passwordValidation())
    {
        if(txtemailAddress.getText().isEmpty()|| txtName.getText().isEmpty() || txtZipCode.getText().isEmpty()|| txtState.getText().isEmpty())
        {
           JOptionPane.showMessageDialog(null, "Compoulsary Felids cannot be empty","Success",JOptionPane.INFORMATION_MESSAGE);
        }
        else{
        PatientInfo patient = patientDir.addPatient();
        patient.setDob(new  Date(z-1900,y-1, x));
        patient.setName(name);
        patient.setPhone(phone);
        patient.setAddressLine1(address);
        patient.setCity(city);
        patient.setState(state);
        patient.setCountry(city);
        patient.setZipCode(zipCode);
        patient.setGender(gender);
        patient.setBloodGroup(txtBloodGroup.getText());
        
        String[] to = {email};
        String from = "patromedi.workspace@gmail.com";
        String pwd = "mavericks3";
        Random rand = new Random();
        int code = rand.nextInt(100000);
        
        String message = "Dear "+ name +",\n\nPlease enter the below code:" + " " +code + "\n\nThanks,\nTeam patroMedi";
        String subject = "Account Verification Mail";
        SendEmailUtility.sendEmail(subject,from, pwd, message, to);
        
        JOptionPane.showMessageDialog(null, "Successfuully recorded the patient details.\nPlease proceed to activate your account.","Success",JOptionPane.INFORMATION_MESSAGE);
        
        ActivatePatientProfileJPanel activateProfile = new ActivatePatientProfileJPanel(displayJPanel,code, patient, system);
        displayJPanel.add("activatePatientProfileJPanel", activateProfile);
        CardLayout layout = (CardLayout) displayJPanel.getLayout();
        layout.next(displayJPanel);
    }
    }
    else
    {
        JOptionPane.showMessageDialog(null, "Please Insert a proper Blood Group","Success",JOptionPane.INFORMATION_MESSAGE);
    }
    
    }
     catch(Exception e){
         JOptionPane.showMessageDialog(null, "Insert Proper values!","Success",JOptionPane.INFORMATION_MESSAGE);
     }
     
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        backAction();
    }//GEN-LAST:event_btnBackActionPerformed

    private void comboMMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboMMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboMMActionPerformed

    private void txtPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    public void backAction()
    {
        displayJPanel.remove(this);
        CardLayout layout = (CardLayout) displayJPanel.getLayout();
        layout.previous(displayJPanel);
    }
    
    public String getGender()
    {
        if(maleRadioBtn.isSelected())
        {
            return "Male";
        }
        else if(femaleRadioBtn.isSelected())
        {
            return "Female";
        }
        
        return null;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox ComboYY;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreate;
    private javax.swing.JComboBox comboDD1;
    private javax.swing.JComboBox comboMM;
    private javax.swing.JRadioButton femaleRadioBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblBloodGroup;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblDOB;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPhoneNumber;
    private javax.swing.JLabel lblPhoto;
    private javax.swing.JLabel lblState;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUserPhoto;
    private javax.swing.JLabel lblZipCode;
    private javax.swing.JRadioButton maleRadioBtn;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtBloodGroup;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtState;
    private javax.swing.JTextField txtZipCode;
    private javax.swing.JTextField txtemailAddress;
    private javax.swing.JButton uploadPicBtn;
    // End of variables declaration//GEN-END:variables
}
