/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Admin;

import Buisness.Enterprise.Enterprise;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author sarthakgoel
 */
public class AdminWorkAreaJPanel extends javax.swing.JPanel 
{
    private JPanel displayJPanel;
    private Enterprise enterprise;
    /**
     * Creates new form AdminWorkAreaJPanel
     */
    public AdminWorkAreaJPanel(JPanel userProcessContainer, Enterprise enterprise) 
    {
        initComponents();
        this.displayJPanel = userProcessContainer;
        this.enterprise = enterprise;
        lblValue.setText(enterprise.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnManageOrg = new javax.swing.JButton();
        btnManageEmp = new javax.swing.JButton();
        btnManageUser = new javax.swing.JButton();
        enterpriseLabel = new javax.swing.JLabel();
        lblValue = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createTitledBorder("Admin Work Area"));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel1.setText("ADMIN WORK AREA");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 38, -1, -1));

        btnManageOrg.setText("Manage Organization");
        btnManageOrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageOrgActionPerformed(evt);
            }
        });
        add(btnManageOrg, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 118, -1, -1));

        btnManageEmp.setText("Manage Employee");
        btnManageEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageEmpActionPerformed(evt);
            }
        });
        add(btnManageEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 168, 177, -1));

        btnManageUser.setText("Manage User");
        btnManageUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageUserActionPerformed(evt);
            }
        });
        add(btnManageUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 218, 177, -1));

        enterpriseLabel.setText("Enterprise -");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 88, 30));
        add(lblValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 90, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageOrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageOrgActionPerformed

        ManageOrganisationJPanel manageOrganization = new ManageOrganisationJPanel(displayJPanel, enterprise);
        displayJPanel.add("manageOrganizationJPanel", manageOrganization);
        CardLayout layout = (CardLayout) displayJPanel.getLayout();
        layout.next(displayJPanel);
    }//GEN-LAST:event_btnManageOrgActionPerformed

    private void btnManageEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageEmpActionPerformed

        ManageEmployeeJPanel manageEmployee = new ManageEmployeeJPanel(displayJPanel, enterprise);
        displayJPanel.add("manageEmployeeJPanel", manageEmployee);

        CardLayout layout = (CardLayout) displayJPanel.getLayout();
        layout.next(displayJPanel);

    }//GEN-LAST:event_btnManageEmpActionPerformed

    private void btnManageUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageUserActionPerformed
        // TODO add your handling code here:
        ManageUserJPanel manageUser = new ManageUserJPanel(displayJPanel, enterprise);
        displayJPanel.add("ManageUserAccountJPanel", manageUser);

        CardLayout layout = (CardLayout) displayJPanel.getLayout();
        layout.next(displayJPanel);
    }//GEN-LAST:event_btnManageUserActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageEmp;
    private javax.swing.JButton btnManageOrg;
    private javax.swing.JButton btnManageUser;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblValue;
    // End of variables declaration//GEN-END:variables
}
