/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Admin;

import Buisness.Enterprise.Enterprise;
import Buisness.Organisation.Organisation.Type;
import Buisness.Organisation.*;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sarthakgoel
 */
public class ManageOrganisationJPanel extends javax.swing.JPanel 
{
    private Enterprise enterprise;
    private OrganisationDirectory organizationDir;
    private JPanel displayJPanel;

    /**
     * Creates new form ManageEmployeeJPanel
     */
    public ManageOrganisationJPanel(JPanel displayJPanel, Enterprise enterprise) 
    {
        initComponents();
        this.displayJPanel = displayJPanel;
        this.enterprise = enterprise;
        this.organizationDir = enterprise.getOrganizationDirectory();
        
        populateCombo();
    }
    
    private void populateCombo()
    {
        organizationJComboBox.removeAllItems();
        
        if(enterprise.getEnterpriseType().equals(Enterprise.EnterpriseType.Hospital))
        {
            for (Type type : Organisation.Type.values())
            {
                if (type.getValue().equals(Type.Doctor.getValue()) || type.getValue().equals(Type.Nurse.getValue()) || type.getValue().equals(Type.Receptionist.getValue()))
                {
                    organizationJComboBox.addItem(type);
                }
            }
        }
        
        else if(enterprise.getEnterpriseType().equals(Enterprise.EnterpriseType.Bloodbank))
        {
            for (Type type : Organisation.Type.values())
            {
                if (type.getValue().equals(Type.BloodBankIncharge.getValue()))
                {
                    organizationJComboBox.addItem(type);
                }
            }
        }
        
        else if(enterprise.getEnterpriseType().equals(Enterprise.EnterpriseType.Charity))
        {
            for (Type type : Organisation.Type.values())
            {
                if (type.getValue().equals(Type.Volunteer.getValue()) || type.getValue().equals(Type.Manager.getValue()))
                {
                    organizationJComboBox.addItem(type);
                }
            }
        }
    }

    private void populateTable()
    {
        DefaultTableModel model = (DefaultTableModel) organizationJTable.getModel();
        model.setRowCount(0);
        
        for (Organisation organization : organizationDir.getOrganizationList())
        {
            Object[] row = new Object[2];
            row[0] = organization.getOrganizationID();
            row[1] = organization.getName();
            
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        organizationJTable = new javax.swing.JTable();
        lblOrgType = new javax.swing.JLabel();
        organizationJComboBox = new javax.swing.JComboBox();
        btnBack = new javax.swing.JButton();
        btnAddOrg = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createTitledBorder("Manage Organisation"));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        organizationJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(organizationJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 68, 480, 92));

        lblOrgType.setText("Organization Type ");
        add(lblOrgType, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 197, -1, -1));

        add(organizationJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 193, 81, -1));

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));

        btnAddOrg.setText("Add Organization>>");
        btnAddOrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddOrgActionPerformed(evt);
            }
        });
        add(btnAddOrg, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, -1, -1));

        lblTitle.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lblTitle.setText("MANAGE ORGANISATION");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 33, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed

        displayJPanel.remove(this);
        CardLayout layout = (CardLayout) displayJPanel.getLayout();
        layout.previous(displayJPanel);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAddOrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddOrgActionPerformed

        Type type = (Type) organizationJComboBox.getSelectedItem();
        organizationDir.createOrganisation(type);
        populateTable();
        
        JOptionPane.showMessageDialog(null, "Organisation Added Successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnAddOrgActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddOrg;
    private javax.swing.JButton btnBack;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblOrgType;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JComboBox organizationJComboBox;
    private javax.swing.JTable organizationJTable;
    // End of variables declaration//GEN-END:variables
}
