/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Nurse;

import Buisness.Bloodbank.Organisation.InchargeOrganisation;
import Buisness.EcoSystem;
import Buisness.Enterprise.BloodbankEnterprise;
import Buisness.Enterprise.Enterprise;
import Buisness.Network.Network;
import Buisness.UserAccount.UserAccount;
import Buisness.WorkQueue.BloodInchargeNurseWorkQueue;
import Buisness.WorkQueue.NurseBloodInchargeWorkQueue;
import Buisness.WorkQueue.WorkRequest;
import Business.Hospital.Organisation.NurseOrganisation;
import UserInterface.SystemAdminWorkArea.SystemAdminWorkAreaJPanel;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aviti
 */
public class NurseBloodBankResponseJPanel extends javax.swing.JPanel {

    /**
     * Creates new form NurseBloodBankResponseJPanel
     */
    
    private JPanel displayJPanel;
    private UserAccount userAccount;
    private NurseOrganisation organisation;
    private EcoSystem system;
    private Network net;
    private UserAccount acc;

   public NurseBloodBankResponseJPanel(JPanel displayJPanel, UserAccount userAccount, NurseOrganisation nurseOrganisation, Enterprise enterprise, Network net, EcoSystem system) {
       initComponents();
       this.displayJPanel=displayJPanel;
       this.acc=userAccount;
       this.organisation=nurseOrganisation;
       this.net=net;
       this.system=system;
       populateTable();
             
    }

    
   

    

    

    
    public void populateTable(){
    
   DefaultTableModel model = (DefaultTableModel) BloodStatusJtable.getModel();
        
        model.setRowCount(0);
       for(WorkRequest request :organisation.getBloodInchargeNurseWQ().getWorkRequestList()){
            BloodInchargeNurseWorkQueue nb = new BloodInchargeNurseWorkQueue();
            nb = (BloodInchargeNurseWorkQueue)request;
            Object[] row = new Object[4];
            row[0] = nb;
            row[1] = nb.getBloodType();
            row[2] = nb.getBloodQuantity();
            row[3]=request.getStatus();
            
            
            model.addRow(row);
        }
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        BloodStatusJtable = new javax.swing.JTable();
        BackjButton = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createTitledBorder("Blood Status"));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BloodStatusJtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Patient Name", "Blood Type", "Quantity of Blood", "Request Status"
            }
        ));
        jScrollPane1.setViewportView(BloodStatusJtable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 87, 494, 165));

        BackjButton.setText("<<Back");
        BackjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackjButtonActionPerformed(evt);
            }
        });
        add(BackjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 296, -1, -1));

        lblTitle.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lblTitle.setText("BLOOD BANK RESPONSE");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 35, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void BackjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackjButtonActionPerformed
        
        
        displayJPanel.remove(this);
        Component[] componentArray = displayJPanel.getComponents();
        Component component = componentArray[componentArray.length - 1];
        NurseWorkAreaJPanel nurse = (NurseWorkAreaJPanel) component;
        CardLayout layout = (CardLayout) displayJPanel.getLayout();
        layout.previous(displayJPanel);
    }//GEN-LAST:event_BackjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackjButton;
    private javax.swing.JTable BloodStatusJtable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
