/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.CharityManager;

import Buisness.Charity.Organisation.ManagerOrganisation;
import Buisness.EcoSystem;
import Buisness.Enterprise.CharityEnterprise;
import Buisness.Network.Network;
import Buisness.UserAccount.UserAccount;
import Buisness.WorkQueue.HospitalCharityRequestWorkQueue;
import Buisness.WorkQueue.WorkRequest;
import Business.Charity.Donation.DonationDetails;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author sarthakgoel
 */
public class ManagerWorkAreaJPanel extends javax.swing.JPanel 
{
    private JPanel displayJPanel;
    private CharityEnterprise enterprise;
    private UserAccount ua;
    private EcoSystem system;
    private Network network;
    String funds;
    /**
     * Creates new form ManagerWorkAreaJPanel
     */
    public ManagerWorkAreaJPanel(JPanel displayJPanel, UserAccount ua, ManagerOrganisation organisation, CharityEnterprise enterprise, Network network, EcoSystem system) 
    {
        initComponents();
        this.displayJPanel = displayJPanel;
        this.enterprise = enterprise;
        this.ua = ua;
        this.system = system;
        this.network = network;
        
        lblValue.setText(enterprise.getName());    
        
        float sumReceived = 0;
        
        try
        {
            for(DonationDetails dd : system.getDonationDirectory().getDonationDirectory())
            {
                if(dd.getCharityName().equalsIgnoreCase(lblValue.getText()))
                {
                    sumReceived += Float.parseFloat(dd.getDonationAmount());
                }
            }
        
            lblFundsValue.setText(String.valueOf(sumReceived));
            float sumUsed = displayFundsUsed();
            float sumAvailable = (sumReceived-sumUsed);
            funds = String.valueOf(sumReceived-sumUsed);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Server Down", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }
    
    public float displayFundsUsed()
    {
        float sum =0;
        
        for(WorkRequest request : network.getCharityRequests().getWorkRequestList())
            {
                HospitalCharityRequestWorkQueue hcrwq = (HospitalCharityRequestWorkQueue)request;
                
                if(hcrwq.getMessage().equalsIgnoreCase("Acknowledged") && hcrwq.getCharityName().equalsIgnoreCase(enterprise.getName()))
                {
                    sum += hcrwq.getAmount();
                }
            }
        
        lblFundsUsed.setText(String.valueOf(sum));
        
        return sum;
    }   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblValue = new javax.swing.JLabel();
        btnViewDonations = new javax.swing.JButton();
        btnPickUp = new javax.swing.JButton();
        lblFunds = new javax.swing.JLabel();
        lblFundsValue = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblFundsUsed = new javax.swing.JLabel();
        btnRefresh = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createTitledBorder("Charity Manager"));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lblTitle.setText("CHARITY MANAGER WORK AREA");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 24, -1, -1));

        lblName.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        lblName.setText("Charity Name");
        add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 77, -1, -1));
        add(lblValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 72, -1, -1));

        btnViewDonations.setText("View Donations");
        btnViewDonations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDonationsActionPerformed(evt);
            }
        });
        add(btnViewDonations, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 243, 163, 76));

        btnPickUp.setText("Pick New Case");
        btnPickUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPickUpActionPerformed(evt);
            }
        });
        add(btnPickUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 243, 163, 76));

        lblFunds.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        lblFunds.setText("Funds Received");
        add(lblFunds, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 119, -1, -1));

        lblFundsValue.setText("value");
        add(lblFundsValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 119, -1, -1));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel1.setText("Funds Used");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 161, -1, -1));

        lblFundsUsed.setText("0");
        add(lblFundsUsed, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 161, -1, -1));

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(357, 72, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewDonationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDonationsActionPerformed
        ViewDonationJPanel viewDonation = new ViewDonationJPanel(displayJPanel, system,enterprise, ua);
        displayJPanel.add("viewDonationJPanel", viewDonation);
        CardLayout layout = (CardLayout) displayJPanel.getLayout();
        layout.next(displayJPanel);
    }//GEN-LAST:event_btnViewDonationsActionPerformed

    private void btnPickUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPickUpActionPerformed
        ViewPatienttoSponsorJPanel patientSponsorship = new ViewPatienttoSponsorJPanel(displayJPanel,enterprise,network,system, ua,funds);
        displayJPanel.add("viewPatienttoSponsorJPanel", patientSponsorship);
        CardLayout layout = (CardLayout) displayJPanel.getLayout();
        layout.next(displayJPanel);
    }//GEN-LAST:event_btnPickUpActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        displayFundsUsed();
    }//GEN-LAST:event_btnRefreshActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPickUp;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnViewDonations;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblFunds;
    private javax.swing.JLabel lblFundsUsed;
    private javax.swing.JLabel lblFundsValue;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblValue;
    // End of variables declaration//GEN-END:variables
}
