/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.Donor;

import Buisness.EcoSystem;
import Buisness.UserInfo.DonorDirectory;
import Buisness.UserInfo.DonorInfo;
import Business.Utilities.SendEmailUtility;
import java.awt.CardLayout;
import java.awt.Image;
import java.io.File;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author sarthakgoel
 */
public class CreateDonorProfileJPanel extends javax.swing.JPanel 
{
    private JPanel displayJPanel;
    private EcoSystem system;
    private DonorDirectory donorDir;

    /** Creates new form CreateDonorProfile */
    public CreateDonorProfileJPanel(JPanel displayJPanel, EcoSystem system) 
    {
        initComponents();
        this.system=system;
        this.displayJPanel=displayJPanel;
        this.donorDir = system.getDonorDir();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblGender = new javax.swing.JLabel();
        maleRadioBtn = new javax.swing.JRadioButton();
        femaleRadioBtn = new javax.swing.JRadioButton();
        lblPhoneNumber = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        lblDOB = new javax.swing.JLabel();
        txtDOB = new javax.swing.JTextField();
        lblAddress = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        lblCity = new javax.swing.JLabel();
        txtCity = new javax.swing.JTextField();
        lblState = new javax.swing.JLabel();
        txtState = new javax.swing.JTextField();
        lblZipCode = new javax.swing.JLabel();
        txtZipCode = new javax.swing.JTextField();
        lblPhoto = new javax.swing.JLabel();
        uploadPicBtn = new javax.swing.JButton();
        btnCreate = new javax.swing.JButton();
        lblUserPhoto = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        txtEmail = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createTitledBorder("Donor Information"));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lblTitle.setText("CREATE DONOR ACCOUNT");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 42, 213, 35));

        lblName.setText("Donor's Name");
        add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 100, -1, -1));
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 95, 149, -1));

        lblGender.setText("Gender");
        add(lblGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 139, -1, -1));

        maleRadioBtn.setBackground(new java.awt.Color(255, 255, 255));
        maleRadioBtn.setText("Male");
        maleRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleRadioBtnActionPerformed(evt);
            }
        });
        add(maleRadioBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 139, -1, -1));

        femaleRadioBtn.setBackground(new java.awt.Color(255, 255, 255));
        femaleRadioBtn.setText("Female");
        femaleRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleRadioBtnActionPerformed(evt);
            }
        });
        add(femaleRadioBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 139, -1, -1));

        lblPhoneNumber.setText("Phone Number");
        add(lblPhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 174, -1, -1));
        add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 174, 149, -1));

        lblDOB.setText("Date Of Birth");
        add(lblDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 218, -1, -1));

        txtDOB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDOBActionPerformed(evt);
            }
        });
        add(txtDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 218, 149, -1));

        lblAddress.setText("Address Line1");
        add(lblAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 262, -1, -1));
        add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 262, 149, -1));

        lblCity.setText("City");
        add(lblCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 306, -1, -1));
        add(txtCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 306, 149, -1));

        lblState.setText("State");
        add(lblState, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 350, -1, -1));
        add(txtState, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 350, 149, -1));

        lblZipCode.setText("ZipCode");
        add(lblZipCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 394, -1, -1));
        add(txtZipCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 394, 149, -1));

        lblPhoto.setText("Upload Photo");
        add(lblPhoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 438, -1, -1));

        uploadPicBtn.setText("Browse");
        uploadPicBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadPicBtnActionPerformed(evt);
            }
        });
        add(uploadPicBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 438, 149, -1));

        btnCreate.setText("CreateProfile>>");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });
        add(btnCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 550, -1, -1));
        add(lblUserPhoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(476, 116, -1, -1));

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, -1, -1));
        add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 480, 150, -1));

        lblEmail.setText("Email");
        add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void uploadPicBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadPicBtnActionPerformed
        try
        {
            JFileChooser userpic = new JFileChooser();
            userpic.showOpenDialog(null);
            File selectedpic = userpic.getSelectedFile();
            String fileName = selectedpic.getAbsolutePath();
            ImageIcon img = new ImageIcon(fileName);
            Image newimage = img.getImage().getScaledInstance(150, 150, Image.SCALE_DEFAULT);
            ImageIcon newicon = new ImageIcon(newimage);

            lblUserPhoto.setIcon(newicon);
            
            //person.getDlInfo().setUserPhoto(fileName);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Photo can not be uploaded. \n Try Again!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_uploadPicBtnActionPerformed

    private void maleRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleRadioBtnActionPerformed
        femaleRadioBtn.setSelected(false);

    }//GEN-LAST:event_maleRadioBtnActionPerformed

    private void femaleRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleRadioBtnActionPerformed
        maleRadioBtn.setSelected(false);

    }//GEN-LAST:event_femaleRadioBtnActionPerformed

    private void txtDOBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDOBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDOBActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed

        try
        {
            String date = txtDOB.getText();
            String name = txtName.getText();
            String gender = getGender();
            String phone = txtPhone.getText();
            String city = txtCity.getText();
            String state = txtState.getText();
            String address = txtAddress.getText();
            int zipCode = Integer.parseInt(txtZipCode.getText());
            String email = txtEmail.getText();
        
            DonorInfo donor = donorDir.addDonor();
            
            if(name != "" && phone != "" && city!= "" && state != "" && address != "" && email != "")
            {
                donor.setName(name);
                donor.setPhone(phone);
                donor.setAddressLine1(address);
                donor.setCity(city);
                donor.setState(state);
                donor.setCountry(city);
                donor.setZipCode(zipCode);
                donor.setGender(gender);
                donor.setEmail(email);
                
            }
        
        String[] to = {email};
        String from = "patromedi.workspace@gmail.com";
        String pwd = "mavericks3";
        Random rand = new Random();
        int code = rand.nextInt(100000);
        
        String message = "Dear "+ name +",\n\nPlease enter the below code:" + " " +code+"\n\nThanks,\nTeam patroMedi";
        String subject = "Account Verification Mail";
        SendEmailUtility.sendEmail(subject,from, pwd, message, to);
        
        JOptionPane.showMessageDialog(null, "Successfully recorded the Donor Details.\nPlease proceed to activate your account.","Success",JOptionPane.INFORMATION_MESSAGE);
        
        ActivateDonorProfileJPanel activateProfile = new ActivateDonorProfileJPanel(displayJPanel,code, donor, system);
        displayJPanel.add("activateDonorProfileJPanel", activateProfile);
        CardLayout layout = (CardLayout) displayJPanel.getLayout();
        layout.next(displayJPanel);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Please enter the valid details", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        backAction();
    }//GEN-LAST:event_btnBackActionPerformed

    public void backAction()
    {
        displayJPanel.remove(this);
        CardLayout layout = (CardLayout) displayJPanel.getLayout();
        layout.previous(displayJPanel);
    }
    
    public String getGender()
    {
        if(maleRadioBtn.isSelected())
        {
            return "Male";
        }
        else if(femaleRadioBtn.isSelected())
        {
            return "Female";
        }
        
        return null;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreate;
    private javax.swing.JRadioButton femaleRadioBtn;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblDOB;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPhoneNumber;
    private javax.swing.JLabel lblPhoto;
    private javax.swing.JLabel lblState;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUserPhoto;
    private javax.swing.JLabel lblZipCode;
    private javax.swing.JRadioButton maleRadioBtn;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtDOB;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtState;
    private javax.swing.JTextField txtZipCode;
    private javax.swing.JButton uploadPicBtn;
    // End of variables declaration//GEN-END:variables

}
