/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Donor;

import Buisness.EcoSystem;
import Buisness.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author sarthakgoel
 */
public class DonorWorkAreaJPanel extends javax.swing.JPanel 
{
    private JPanel displayJPanel;
    private EcoSystem system;
    private UserAccount ua;

    /**
     * Creates new form DonorWorkAreaJPanel
     */
    public DonorWorkAreaJPanel(JPanel displayJPanel,UserAccount account, EcoSystem ecosystem) 
    {
        initComponents();
        this.system=ecosystem;
        this.displayJPanel=displayJPanel;
        this.ua = account;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        btnNewDonation = new javax.swing.JButton();
        btnDonationHistory = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createTitledBorder("Donor Work Area"));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lblTitle.setText("DONOR WORK AREA");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 24, 184, 29));

        btnNewDonation.setText("Make a Donation");
        btnNewDonation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewDonationActionPerformed(evt);
            }
        });
        add(btnNewDonation, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 92, 203, -1));

        btnDonationHistory.setText("Donation History");
        btnDonationHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDonationHistoryActionPerformed(evt);
            }
        });
        add(btnDonationHistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 139, 203, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewDonationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewDonationActionPerformed
        NewDonationJPanel donation = new NewDonationJPanel(displayJPanel, system, ua);
        displayJPanel.add("newDonationJPanel", donation);
        CardLayout layout = (CardLayout) displayJPanel.getLayout();
        layout.next(displayJPanel);
    }//GEN-LAST:event_btnNewDonationActionPerformed

    private void btnDonationHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDonationHistoryActionPerformed
        
        DonorDonationHistoryJPanel donationHistory = new DonorDonationHistoryJPanel(displayJPanel, system, ua);
        displayJPanel.add("donorDonationHistoryJPanel", donationHistory);
        CardLayout layout = (CardLayout) displayJPanel.getLayout();
        layout.next(displayJPanel);
    }//GEN-LAST:event_btnDonationHistoryActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDonationHistory;
    private javax.swing.JButton btnNewDonation;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
