/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Receptionist;

import Buisness.EcoSystem;
import Buisness.Employee.Employee;
import Buisness.Enterprise.Enterprise;
import Buisness.Network.Network;
import Buisness.Organisation.Organisation;
import Buisness.UserAccount.UserAccount;
import java.util.Date;
import javax.swing.JPanel;
import Buisness.WorkQueue.ReceptionistAddSlotsWorkQueue;
import java.awt.CardLayout;
import javax.swing.JOptionPane;


/**
 *
 * @author aviti
 */
public class ReceptionistAppointmentAreaJPanel extends javax.swing.JPanel 
{
    private JPanel displayJpanel;
    private Enterprise enterprise;
    private EcoSystem system;
    private Network network;
    private UserAccount useraccunt;
    private ReceptionistAddSlotsWorkQueue receptionslot;
    /**
     * Creates new form ReceptionistAppointmentAreaJPanel
     */
    public ReceptionistAppointmentAreaJPanel(JPanel displayJpanel,UserAccount userAccount,Enterprise enterprise,Network network ,EcoSystem system) 
    {   
        initComponents();
        
        this.displayJpanel = displayJpanel;
        this.enterprise = enterprise;
        this.system = system;
        this.useraccunt = userAccount;
        this.network = network;
        lblValue.setText(userAccount.getUsername());
        populateJcomboBbox();
    }
    
    public void populateJcomboBbox()
    {
        comboTime.removeAllItems();
        for(Organisation o : enterprise.getOrganizationDirectory().getOrganizationList()){
            if(o.getName().equals("Doctor Organisation"))
            {
                for(Employee e: o.getEmployeeDirectory().getEmployeeList())
                {
                    comboTime.addItem(e);
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        AcceptjButton = new javax.swing.JButton();
        lblValue = new javax.swing.JLabel();
        comboMM = new javax.swing.JComboBox();
        comboDD1 = new javax.swing.JComboBox();
        ComboYY = new javax.swing.JComboBox();
        comboTime = new javax.swing.JComboBox();
        lblDocName = new java.awt.Label();
        lblDate = new java.awt.Label();
        lblName = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Receptionist"));

        lblTitle.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lblTitle.setText("RECEPTIONIST WORK AREA");

        AcceptjButton.setText("Add>>");
        AcceptjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcceptjButtonActionPerformed(evt);
            }
        });

        comboMM.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        comboDD1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        ComboYY.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2018", "2019", "2020", " " }));
        ComboYY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboYYActionPerformed(evt);
            }
        });

        comboTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTimeActionPerformed(evt);
            }
        });

        lblDocName.setText("Doctor Name");

        lblDate.setText("Date(MM-DD-YY)");

        lblName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblName.setText("Receptionist");

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDocName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblDate, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(76, 76, 76)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(comboTime, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(comboMM, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(comboDD1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(ComboYY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnBack)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(AcceptjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblName)
                            .addComponent(lblTitle))
                        .addGap(32, 32, 32)
                        .addComponent(lblValue, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(267, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblValue, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDocName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(comboMM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(comboDD1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ComboYY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(74, 74, 74)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AcceptjButton)
                    .addComponent(btnBack))
                .addContainerGap(208, Short.MAX_VALUE))
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void ComboYYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboYYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboYYActionPerformed

    private void comboTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboTimeActionPerformed

    private void AcceptjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcceptjButtonActionPerformed
       String dd,mm,yy;
           dd = (String)comboDD1.getSelectedItem();
           mm = (String)comboMM.getSelectedItem();
           yy = (String)ComboYY.getSelectedItem();
           int x,y,z;
           x = Integer.parseInt(dd);
           y = Integer.parseInt(mm);
           z = Integer.parseInt(yy);
           
           
           
           receptionslot = new ReceptionistAddSlotsWorkQueue();
           
           receptionslot.setSlot(new  Date(z-1900,y-1, x));
           for(Network n : system.getNetworkList())
           {
               for(Enterprise e : n.getEnterpriseDirectory().getEnterpriseList())
               {
                   if(e.getName().equalsIgnoreCase(enterprise.getName()))
                   {
                       receptionslot.setCity(n.getName());
                   }
               }
           }
           Employee e = new Employee();
           e = (Employee)comboTime.getSelectedItem();
           
           receptionslot.setDoctor(e.getName());
           receptionslot.setSender(useraccunt);
           receptionslot.setStatus("Available");
           receptionslot.setMessage("lul");
           receptionslot.setHospitalName(enterprise.getName());
           receptionslot.setCity(network.getName());
           system.getPatientDir().getWorkQueue().getWorkRequestList().add(receptionslot);
           useraccunt.getWorkQueue().getWorkRequestList().add(receptionslot);
            
           JOptionPane.showMessageDialog(null, "Doctor's Slot added successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_AcceptjButtonActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        displayJpanel.remove(this);
        CardLayout layout = (CardLayout) displayJpanel.getLayout();
        layout.previous(displayJpanel);;
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AcceptjButton;
    private javax.swing.JComboBox ComboYY;
    private javax.swing.JButton btnBack;
    private javax.swing.JComboBox comboDD1;
    private javax.swing.JComboBox comboMM;
    private javax.swing.JComboBox comboTime;
    private javax.swing.JPanel jPanel2;
    private java.awt.Label lblDate;
    private java.awt.Label lblDocName;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblValue;
    // End of variables declaration//GEN-END:variables
}
