/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Receptionist;

import Buisness.EcoSystem;
import Buisness.Enterprise.Enterprise;
import Buisness.Network.Network;
import Buisness.UserAccount.UserAccount;
import Business.Hospital.Organisation.ReceptionistOrganisation;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author manor
 */
public class ReceptionistLandingPage extends javax.swing.JPanel {

    /**
     * Creates new form ReceptionistLandingPage
     */
    private JPanel dispJPanel;
    private UserAccount account;
    private ReceptionistOrganisation organisation;
    private Enterprise enterprise;
    private EcoSystem system;
    private Network net;
    public ReceptionistLandingPage(JPanel userProcessContainer, UserAccount account, ReceptionistOrganisation organisation, Enterprise enterprise,Network net,EcoSystem system) 
    {
        initComponents();
        this.dispJPanel = userProcessContainer;
        this.account = account;
        this.organisation = organisation;
        this.enterprise = enterprise;
        this.system = system;
        this.net = net;
        
        lblValue.setText(account.getUsername());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AddButton = new javax.swing.JButton();
        ViewApptButton = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        lblValue = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        btnCreateFundingRequests = new javax.swing.JButton();
        btnViewCharityRequests = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createTitledBorder("Receptionist Landing Page"));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AddButton.setText("Add Doctor Slots");
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });
        add(AddButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 173, 180, 66));

        ViewApptButton.setText("View Patient Requests");
        ViewApptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewApptButtonActionPerformed(evt);
            }
        });
        add(ViewApptButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, 170, 66));

        lblTitle.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lblTitle.setText("RECEPTIONIST LANDING AREA");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 38, -1, 34));
        add(lblValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 84, 74, 30));

        lblName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblName.setText("Receptionist");
        add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 84, -1, 30));

        btnCreateFundingRequests.setText("Create Funding Requests");
        btnCreateFundingRequests.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateFundingRequestsActionPerformed(evt);
            }
        });
        add(btnCreateFundingRequests, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 180, 60));

        btnViewCharityRequests.setText("View Charity Response");
        btnViewCharityRequests.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewCharityRequestsActionPerformed(evt);
            }
        });
        add(btnViewCharityRequests, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 280, 170, 60));
    }// </editor-fold>//GEN-END:initComponents

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
        ReceptionistAppointmentAreaJPanel rajp =new  ReceptionistAppointmentAreaJPanel(dispJPanel,account,enterprise,net,system);
        dispJPanel.add("ReceptionistAppointment",rajp);
        CardLayout layout=(CardLayout)dispJPanel.getLayout();
        layout.next(dispJPanel);
    }//GEN-LAST:event_AddButtonActionPerformed

    private void ViewApptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewApptButtonActionPerformed
        // TODO add your handling code here:
        ReceptionistWorkAreaJPanel rwjp =new  ReceptionistWorkAreaJPanel(dispJPanel,account,organisation,enterprise,system);
        dispJPanel.add("ReceptionistWorkArea",rwjp);
        CardLayout layout=(CardLayout)dispJPanel.getLayout();
        layout.next(dispJPanel);
    }//GEN-LAST:event_ViewApptButtonActionPerformed

    private void btnViewCharityRequestsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewCharityRequestsActionPerformed
        
        CharityAcknowledgementJPanel ca =new  CharityAcknowledgementJPanel(dispJPanel,account,organisation,enterprise,net,system);
        dispJPanel.add("charityAcknowledgementJPanel",ca);
        CardLayout layout=(CardLayout)dispJPanel.getLayout();
        layout.next(dispJPanel);
    }//GEN-LAST:event_btnViewCharityRequestsActionPerformed

    private void btnCreateFundingRequestsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateFundingRequestsActionPerformed
        CreateCharityFundingRequestsJPanel ccfrjp =new CreateCharityFundingRequestsJPanel(dispJPanel,account,organisation,enterprise,net,system);
        dispJPanel.add("ReceptionistWorkArea",ccfrjp);
        CardLayout layout=(CardLayout)dispJPanel.getLayout();
        layout.next(dispJPanel);
    }//GEN-LAST:event_btnCreateFundingRequestsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JButton ViewApptButton;
    private javax.swing.JButton btnCreateFundingRequests;
    private javax.swing.JButton btnViewCharityRequests;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblValue;
    // End of variables declaration//GEN-END:variables
}
